#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  fileExists,
  getArg,
  getPhaseSlug,
  readJsonFile,
  readState,
  readTextFile,
  resolvePackageRoot
} from './mvp-builder-package-utils';

type RequirementEntry = {
  id: string;
  title: string;
};

type PhaseEntry = {
  index: number;
  slug: string;
  name: string;
  requirementIds: string[];
};

function parseRequirements(packageRoot: string): RequirementEntry[] {
  const reqPath = path.join(packageRoot, 'requirements', 'FUNCTIONAL_REQUIREMENTS.md');
  if (!fileExists(reqPath)) return [];
  const content = readTextFile(reqPath);
  const matches = Array.from(content.matchAll(/##\s+Requirement\s+(\d+):\s*([^\n]+)/g));
  return matches.map((match) => ({
    id: `REQ-${match[1]}`,
    title: match[2].trim()
  }));
}

function parsePhases(packageRoot: string): PhaseEntry[] {
  const phasePlanPath = path.join(packageRoot, 'PHASE_PLAN.md');
  if (!fileExists(phasePlanPath)) return [];
  const content = readTextFile(phasePlanPath);
  const phaseMatches = Array.from(content.matchAll(/##\s+(\d+)\.\s+([^\n]+)\n([\s\S]*?)(?=\n##\s+\d+\.|$)/g));
  return phaseMatches.map((match) => {
    const index = Number.parseInt(match[1], 10);
    const name = match[2].trim();
    const body = match[3];
    const reqLine = body.match(/Requirement IDs?:\s*([^\n]+)/i)?.[1] || '';
    const requirementIds = reqLine
      .split(/[,\s]+/)
      .map((token) => token.trim())
      .filter((token) => /^REQ[-_]?\d+$/i.test(token))
      .map((token) => token.replace(/_/g, '-').toUpperCase());
    return { index, slug: getPhaseSlug(index), name, requirementIds };
  });
}

function buildMatrix(requirements: RequirementEntry[], phases: PhaseEntry[]) {
  const reqToPhases = new Map<string, string[]>();
  for (const req of requirements) reqToPhases.set(req.id, []);
  for (const phase of phases) {
    for (const reqId of phase.requirementIds) {
      const list = reqToPhases.get(reqId) || [];
      list.push(phase.slug);
      reqToPhases.set(reqId, list);
    }
  }
  return reqToPhases;
}

function renderTraceabilityDoc(args: {
  requirements: RequirementEntry[];
  phases: PhaseEntry[];
  reqToPhases: Map<string, string[]>;
  phaseEvidence: Record<
    string,
    {
      approvedToProceed: boolean;
      reviewerRecommendation: string;
      evidenceFiles: string[];
      attempts?: Array<{ attempt: number; status: string }>;
    }
  >;
  unmappedRequirementCount: number;
}) {
  const lines: string[] = [];
  lines.push('# TRACEABILITY');
  lines.push('');
  lines.push(
    'This file maps numbered requirements to the phases that own them and the evidence that proves them. It is generated by `npm run traceability` and reflects the current state of `PHASE_PLAN.md`, `requirements/FUNCTIONAL_REQUIREMENTS.md`, and `repo/mvp-builder-state.json`.'
  );
  lines.push('');
  lines.push('## Coverage summary');
  lines.push(`- Requirements declared: ${args.requirements.length}`);
  lines.push(`- Requirements mapped to at least one phase: ${args.requirements.length - args.unmappedRequirementCount}`);
  lines.push(`- Requirements with no phase assignment: ${args.unmappedRequirementCount}`);
  lines.push('');
  lines.push('## Requirement to phase matrix');
  lines.push('');
  if (args.requirements.length === 0) {
    lines.push('_No numbered requirements were detected in `requirements/FUNCTIONAL_REQUIREMENTS.md`._');
    lines.push('');
  } else {
    lines.push('| Requirement | Title | Phases | Status |');
    lines.push('| --- | --- | --- | --- |');
    for (const req of args.requirements) {
      const phases = args.reqToPhases.get(req.id) || [];
      const statuses = phases.map((slug) => {
        const evidence = args.phaseEvidence[slug];
        if (!evidence) return `${slug}: no evidence`;
        const attemptCount = evidence.attempts?.length || 0;
        const recommendation = evidence.reviewerRecommendation || 'pending';
        return `${slug}: ${recommendation}${attemptCount > 0 ? ` (${attemptCount} attempt${attemptCount === 1 ? '' : 's'})` : ''}`;
      });
      const phaseCell = phases.length ? phases.join(', ') : '_unassigned_';
      const statusCell = statuses.length ? statuses.join('; ') : '_no phase owns this requirement_';
      lines.push(`| ${req.id} | ${req.title.replace(/\|/g, '\\|')} | ${phaseCell} | ${statusCell} |`);
    }
    lines.push('');
  }

  lines.push('## Phase to requirement matrix');
  lines.push('');
  if (args.phases.length === 0) {
    lines.push('_No phases were detected in `PHASE_PLAN.md`._');
    lines.push('');
  } else {
    lines.push('| Phase | Name | Requirements | Approved | Attempts |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const phase of args.phases) {
      const evidence = args.phaseEvidence[phase.slug];
      const approved = evidence?.approvedToProceed ? 'yes' : 'no';
      const attempts = evidence?.attempts?.length || 0;
      const reqs = phase.requirementIds.length ? phase.requirementIds.join(', ') : '_unassigned_';
      lines.push(`| ${phase.slug} | ${phase.name.replace(/\|/g, '\\|')} | ${reqs} | ${approved} | ${attempts} |`);
    }
    lines.push('');
  }

  lines.push('## How to add a phase-to-requirement mapping');
  lines.push('');
  lines.push('1. In `PHASE_PLAN.md`, under each phase heading, add a line:');
  lines.push('');
  lines.push('   ```');
  lines.push('   - Requirement IDs: REQ-3, REQ-7, REQ-12');
  lines.push('   ```');
  lines.push('');
  lines.push('2. In `requirements/FUNCTIONAL_REQUIREMENTS.md`, keep numbered headings as `## Requirement N: Title`.');
  lines.push('3. Re-run `npm run traceability` to refresh this file.');
  lines.push('');
  lines.push('Unassigned requirements are not a hard failure, but they should be triaged before release.');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

export function runTraceability() {
  const packageRoot = resolvePackageRoot(getArg('package'));
  const state = readState(packageRoot);
  // Tolerate package without manifest.
  let manifestPhaseCount = 0;
  try {
    const manifest = readJsonFile<{ phaseCount?: number }>(path.join(packageRoot, 'repo', 'manifest.json'));
    manifestPhaseCount = manifest.phaseCount || 0;
  } catch {
    manifestPhaseCount = 0;
  }

  const requirements = parseRequirements(packageRoot);
  const phases = parsePhases(packageRoot);
  if (phases.length === 0 && manifestPhaseCount > 0) {
    for (let i = 1; i <= manifestPhaseCount; i += 1) {
      phases.push({ index: i, slug: getPhaseSlug(i), name: `Phase ${i}`, requirementIds: [] });
    }
  }
  const reqToPhases = buildMatrix(requirements, phases);
  const unmappedRequirementCount = Array.from(reqToPhases.values()).filter((list) => list.length === 0).length;

  const doc = renderTraceabilityDoc({
    requirements,
    phases,
    reqToPhases,
    phaseEvidence: state.phaseEvidence,
    unmappedRequirementCount
  });

  const repoDir = path.join(packageRoot, 'repo');
  if (!fs.existsSync(repoDir)) fs.mkdirSync(repoDir, { recursive: true });
  const outputPath = path.join(repoDir, 'TRACEABILITY.md');
  fs.writeFileSync(outputPath, doc, 'utf8');
  console.log(`Wrote traceability matrix to: ${path.relative(packageRoot, outputPath).replace(/\\/g, '/')}`);
  console.log(
    `Requirements: ${requirements.length}, phases: ${phases.length}, unmapped requirements: ${unmappedRequirementCount}`
  );
}

const isDirectRun = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectRun) {
  try {
    runTraceability();
  } catch (error) {
    console.error((error as Error).message);
    process.exit(1);
  }
}
